# -*- coding: utf-8 -*-
"""DataPreprocessng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13v6-tBVxhh2Q9SbJS1XW1VEFqDMioFcn
"""

import numpy as np

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler


df=pd.read_csv('/content/Iris.csv')
# print(df.isnull().sum())

print("Dataset info:",df.info())
print(df.head())

df.drop('Id',axis=1,inplace=True)
print(df)

print("Before",df.isnull().sum())
df.dropna(inplace=True)
print("After",df.isnull().sum())

label_encoder=LabelEncoder()
df['Species']=label_encoder.fit_transform(df['Species'])
print(df)

X=df.drop('Species',axis=1)
y=df['Species']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

print("Before scaling :",X_train)
print("After scaling :",X_train_scaled[:5])