# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D68QmDPtjMQN_DZgAc5vsPpVb78pG-ih
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


df=pd.read_csv("/content/Student_Marks.csv")
#print(df.head())
print(df.isnull().sum())

X=df[['time_study']]
Y=df['Marks']

# print(X)
# print(Y)


X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)



model = LinearRegression()
model.fit(X_train, Y_train)

print("Intercept:", model.intercept_)
print("Coefficient:", model.coef_)

y_pred = model.predict(X_test)

print("Mean Square error :",mean_squared_error(Y_test,y_pred))
print("R2 Score :",r2_score(Y_test,y_pred))

X_test_sorted=X_test.sort_values(by='time_study')
Y_test_sorted=model.predict(X_test_sorted)

plt.scatter(X_test, Y_test, color='blue', label='Study_Time')
plt.plot(X_test_sorted, Y_test_sorted, color='green', label='Marks Obtained')

plt.xlabel('X')
plt.ylabel('Y')
plt.title('Simple Linear Regression')
plt.legend()
plt.grid(True)
plt.show()

residual=Y_test-y_pred

plt.scatter(y_pred,residual)
plt.axhline(y=0,color='r',linestyle='--')
plt.xlabel('Y_pred')
plt.ylabel('Residual')
plt.title('Residual Plot')
plt.legend()
plt.grid(True)
plt.show()